### ISSUE TITLE
global app style

### ISSUE THREAD

**Issue by mar-bi** [chingu-voyage3/bears-16#16]
origin is at #14
moved from #8  
There is a small issue with CSS - an existing CSS file `\layouts\index.css` takes a precedence over `\theme\globalStyle.js`.
Basically, `\layouts\index.css` came with `gatsby-starter` and contains almost a reset together with vendor prefixes.
`styled-components` handles **vendor** prefixes on its own.    
So we can comment out `\layouts\index.css` or delete this file completely in future.

**Comment by mar-bi** [comment]
As a great fan of **Sass**, I would like to add the chosen **Color Palette** to `\theme\globalStyle.js`.
Referencing it in this way, we can keep colors through the app and alter them, if there would be a necessity.   
```
export const ColorPalette = {
  text: "#333",
  white: "#fff",
  primary: {
    dark: "#453463",
    light: "#755f9f"
  },
  secondary: {
    green: "#8ac3a9",
    yellow: "#fcdeb6",
    red: "#ff8463"
  },
  shades: {
    //add shades with progress
  }
}
```
Just import and use it.
```
import { StyledH1, StyledUl, StyledLi, ColorPalette as CP } from "../theme/globalStyle";

const BrandTitle = StyledH1.extend`
  grid-area: brand;
  color: ${CP.primary.light};
  font-size: 1.6em;
  padding: 0.5rem;
`;
```

**Comment by spences10** [comment]
Awesome @mar-bi 👌 

I'll pick this up if you like?

**Comment by mar-bi** [comment]
Great! Pick it up! :+1:
