### ISSUE TITLE
add Faker

### ISSUE THREAD

**Issue by mar-bi** [chingu-voyage3/bears-16#7]
https://www.npmjs.com/package/Faker

**Comment by spences10** [comment]
So, this will [could] be a dev dependency

There's no real need other than to have some dummy data to go onto the pages

It could be added into the `package.json` it'll be a 2 minute task

I'll happily do it just to get it off of the issues list 🙃 

I'll pick this up in the morning if that's ok with you @mar-bi ?? 🤔

**Comment by mar-bi** [comment]
It's ok. 👌
Please,  pick up it and close this issue.👍
